GENERAL:
  delay: 20
  noise: 0
INSTANTIATE:
  - name: distinct
    type: B
    params:
      bg: red
      fg: red
    duration:
      mu: 6
      sigma: 2

  - name: e1
    type: B
    params:
      bg: red
      fg: red
    duration:
      mu: 6
      sigma: 2

  - name: d1
    type: B
    params:
      bg: red
      fg: red
    duration:
      mu: 6
      sigma: 2

RELATIONSHIP:
  - type: met_by
    events:
        - e1
        - d1

  - type: after
    events:
      - distinct
      - e1
    other:
      gap_dist:
        mu: 2
        sigma: 1